export enum EstadoPedido {
    ACEPTADO = 'ACEPTADO',
    RECHAZADO = 'RECHAZADO',
    EN_PREPARACION = 'EN_PREPARACION',
    LISTO_PARA_RETIRAR = 'LISTO_PARA_RETIRAR',
    PRONTO_A_SER_SERVIDO = 'PRONTO_A_SER_SERVIDO',
  }
  